import { GameManager } from '../managers/GameManager';
import { SettingsManager } from '../managers/SettingsManager';
import { AssetLoader } from '../managers/AssetLoader';
import { DiagnosticFXPipeline, DIAGNOSTIC_FX } from '../fx/DiagnosticFXPipeline';
import { RadDialConfig } from '../types/RadDialTypes';
import { DRONE_FILE_MANIFEST, EXPLOSION_MANIFEST, ACTION_ITEMS_MANIFEST } from '../generated/SpritesManifest';

export class Preloader extends Phaser.Scene {
  constructor() {
    super('Preloader');
  }

  preload() {
    // Wire up loading-bar progress so the indeterminate sweep transitions to a
    // deterministic fill once Phaser starts reporting actual load progress.
    const fill = document.getElementById('loading-bar-fill');
    if (fill) {
      this.load.on('progress', (value: number) => {
        fill.style.animation  = 'none';
        fill.style.transform  = 'none';
        fill.style.width      = `${Math.round(value * 100)}%`;
      });
    }

    // Load config and core data
    this.load.json('config',   'data/config.json');
    this.load.json('rad-dial', 'data/rad-dial.json');

    // Queue per-mode item files immediately after rad-dial.json is registered
    // so they all download in parallel.  Each file is cached under the action id
    // (e.g. 'action_reorient') which GameManager reads back in create().
    // We read the JSON synchronously here because the file list is embedded in
    // a tiny inline config object, not a network request — Phaser queues it
    // before the XHR batch fires, so the keys are set when progress reaches 1.
    //
    // Note: a proper two-pass load (load rad-dial first, callback to load mode
    // files) would require an extra Phaser load cycle. Instead we replicate the
    // action list here as a constant that must stay in sync with rad-dial.json.
    // The runtime path (GameManager.buildModeStores) is tolerant of missing keys.
    const radDial = this.cache?.json?.get('rad-dial') as RadDialConfig | null;
    if (radDial) {
      for (const action of radDial.actions) {
        if (action.itemsFile) {
          this.load.json(action.id, action.itemsFile);
        }
      }
    } else {
      // Fallback: rad-dial.json not yet in cache (first call before XHR batch).
      // Hardcode the mode file list so they still load in the same batch.
      const MODE_FILES: Array<[string, string]> = [
        ['action_reorient', 'data/modes/reorient/items.json'],
        ['action_replace',  'data/modes/replace/items.json'],
        ['action_rewire',   'data/modes/rewire/items.json'],
        ['action_rebuild',  'data/modes/rebuild/items.json'],
        ['action_refuel',   'data/modes/refuel/items.json'],
        ['action_recharge', 'data/modes/recharge/items.json'],
      ];
      for (const [key, path] of MODE_FILES) {
        this.load.json(key, path);
      }
    }

    for (const [key, path] of DRONE_FILE_MANIFEST) {
      this.load.image(key, path);
    }

    for (const [key, path, frameSize] of EXPLOSION_MANIFEST) {
      this.load.spritesheet(key, path, { frameWidth: frameSize, frameHeight: frameSize });
    }

    // Action-item icons — standalone PNGs for each active action type.
    // ACTION_ITEMS_MANIFEST is generated by scripts/generate_manifests.js from
    // public/assets/<action>/ folders and stays in sync automatically.
    for (const entries of Object.values(ACTION_ITEMS_MANIFEST)) {
      for (const [key, path] of entries) {
        this.load.image(key, path);
      }
    }

    // Parallax background layers — 8 sets × 2 time-of-day variants × 5 layers = 80 images.
    // Key convention: `bg-{set}-{tod}-{layer}`  e.g. `bg-3-night-2`
    for (let set = 1; set <= 8; set++) {
      for (const tod of ['Day', 'Night'] as const) {
        for (let layer = 1; layer <= 5; layer++) {
          this.load.image(
            `bg-${set}-${tod.toLowerCase()}-${layer}`,
            `assets/backgrounds/${set}/${tod}/${layer}.png`,
          );
        }
      }
    }

    // Artifact animations — alpha and beta collections, 20 spritesheets each; 4 frames of 20×20 px.
    // Keys: artifact-alpha-{n}, artifact-beta-{n}
    for (let n = 1; n <= 20; n++) {
      this.load.spritesheet(`artifact-alpha-${n}`, `assets/artifacts/alpha/${n}.png`,  { frameWidth: 20, frameHeight: 20 });
      this.load.spritesheet(`artifact-beta-${n}`,  `assets/artifacts/beta/${n}.png`,   { frameWidth: 20, frameHeight: 20 });
    }

    // Sprite atlases — queued here so they download in parallel with the
    // drone/robot/background sprites rather than after a sequential create() chain.
    AssetLoader.preloadAtlases(this);
  }

  async create() {
    try {
      // Register diagnostic wireframe PostFX pipeline (WebGL only — no-op in Canvas)
      if (this.game.renderer.type === Phaser.WEBGL) {
        const r = this.game.renderer as Phaser.Renderer.WebGL.WebGLRenderer;
        if (!r.pipelines.has(DIAGNOSTIC_FX)) {
          r.pipelines.addPostPipeline(DIAGNOSTIC_FX, DiagnosticFXPipeline);
        }
      }

      // Initialize managers in parallel — GameManager reads from the Phaser JSON
      // cache (populated in preload()); SettingsManager reads localStorage or
      // fetches the tiny settings.json. Neither blocks on a network round-trip.
      const gameManager     = GameManager.getInstance();
      const settingsManager = SettingsManager.getInstance();
      await Promise.all([
        gameManager.initialize(this, 'data/config.json'),
        settingsManager.loadSettings(),
      ]);

      const config = gameManager.getConfig();

      // If a one-off root-dial icon is configured, load it now (rare case).
      if (config.rootDialIconPath) {
        this.load.image('rootDialIcon', config.rootDialIconPath);
        this.load.start();
        await new Promise<void>(resolve => this.load.once('complete', resolve));
      }
      
      // Register artifact animations (4-frame horizontal strips at 8 fps).
      for (const col of ['alpha', 'beta']) {
        for (let n = 1; n <= 20; n++) {
          const key = `artifact-${col}-${n}`;
          if (!this.anims.exists(key) && this.textures.exists(key)) {
            this.anims.create({
              key,
              frames:    this.anims.generateFrameNumbers(key, { start: 0, end: 3 }),
              frameRate: 8,
              repeat:    -1,
            });
          }
        }
      }

      // Register explosion animations — play-once at 12 fps.
      // Keys come from the generated EXPLOSION_MANIFEST so new tiers auto-register.
      for (const [key] of EXPLOSION_MANIFEST) {
        if (!this.anims.exists(key) && this.textures.exists(key)) {
          this.anims.create({
            key,
            frames:    this.anims.generateFrameNumbers(key, { start: 0, end: -1 }),
            frameRate: 12,
            repeat:    0,
          });
        }
      }

      // Warm up web fonts: the hidden font-primer elements in index.html force the
      // browser to download the font files via CSS. document.fonts.ready resolves
      // only after all referenced @font-face fonts finish loading.
      await document.fonts.ready;

      // Probe Text objects prime the Phaser/canvas font metric cache so the canvas
      // 2D context has measured the glyphs before any visible scene draws.
      const _m = this.add.text(-9999, -9999, 'AaBbCc', { fontFamily: 'Minotaur', fontSize: '16px', color: '#000000' });
      const _h = this.add.text(-9999, -9999, '0123456789', { fontFamily: 'Hack', fontSize: '16px', color: '#000000' });

      // One rAF tick so the canvas context actually renders (and caches) the probes.
      await new Promise<void>(resolve => requestAnimationFrame(() => resolve()));

      // All assets and fonts are ready — dismiss the HTML loading screen.
      document.getElementById('loading-screen')?.remove();

      // Transition to MainMenu
      this.scene.start('MainMenu');
      _m.destroy();
      _h.destroy();
    } catch (error) {
      console.error('Failed to initialize game:', error);
      document.getElementById('loading-screen')?.remove();
      // Fallback to MainMenu anyway for now
      this.scene.start('MainMenu');
    }
  }
}